# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, djiki.models.Versioned),
        ),
        migrations.CreateModel(
            name='ImageRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Description')),
                ('file', models.FileField(upload_to=b'djimages/', verbose_name='File')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='djiki.Image')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(models.Model, djiki.models.Versioned),
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='djiki.Page')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
